### PR TITLE
Tutorials for Galerkin ROMs

### PR DESCRIPTION
**Pull request by MikolajZuzek**
Part of #16

### Contents
* [x] known types tutorials
  - [x] masked Galerkin - explicit and implicit
  - [x] hyper-reduced Galerkin - explicit and implicit
* [x] cutom types tutorials
  - [x] default Galerkin - implicit
  - [x] masked Galerkin - explicit and implicit
  - [x] hyper-reduced Galerkin - explicit and implicit
* [ ] verify implicit results by hand ?

📌 [See the HTML preview for this PR](https://htmlpreview.github.io/?https://github.com/Pressio/pressio-tutorials/blob/16-rom-tutorials/docs/index.html)

### CODE REVIEW

**Comment by fnrizzi** [comment]
@MikolajZuzek how do you generat the html preview?? that is pretty awesome !

**Comment by MikolajZuzek** [comment]
@fnrizzi Thanks to kind people from https://htmlpreview.github.io/,  you can go to that website and paste link to a HTML file stored in GitHub repository - like https://github.com/Pressio/pressio-tutorials/blob/16-rom-tutorials/docs/index.html for our generated docs - then press `Preview` button to generate the page with all cool styling in effect. Once the preview pops up in the browser, you can just copy the link and reuse where needed.  
I guess you can also figure out how to construct the magic preview link directly from GitHub link.

**Comment by fnrizzi** [comment]
@MikolajZuzek this looks really good! 
I will check in more detail but one thing if I may ask you to add: can you please add the following sentence to the top of each ROM tutorials webpage? RIght after the title, for now I would like to have this:

```
This tutorial has been taken directly from the C++ tests. We will adapt/update this soon with more details and descriptions. 
```

**Comment by MikolajZuzek** [comment]
@fnrizzi Added the line as you suggested - let me know if there's anything else to fix.

**Pull request merged**
